### PR TITLE
Parameterized file reader

### PR DESCRIPTION
**Pull request by david-christiansen**
This updates cryptol-verifier to still work with the changes made in https://github.com/GaloisInc/cryptol/pull/793.

### CODE REVIEW

**Comment by david-christiansen** [comment]
These changes were made based on the commit in the submodule in saw-script, and it seems to include things that are not in master here. How should I proceed?

**Comment by brianhuffman** [comment]
It looks like @robdockins did that with GaloisInc/saw-script@680edad966fe67544a3eb54ffaa028c940ca5cc0. It looks like we need to merge the `split-arith` branch of `cryptol-verifier` into `master`. It looks like `split-arith` actually was merged into `master` at one point (with #17), but maybe Rob kept pushing to that branch afterward?

**Comment by robdockins** [comment]
I think that all the relevant code changes eventually got rebased into master, although I guess it's possible I missed something along the way.  That rebase got pretty hairy.

I think you should be able to rebase this branch onto master without too much trouble, or maybe just cherry-pick your commit.

**Comment by brianhuffman** [comment]
I was really confused looking at the saw-script git history, because I was trying to see which PR Rob's "update submodules" commit (GaloisInc/saw-script@680edad) was part of, and there wasn't any merge commit at all, even though it looks like all the other PRs have merge commits.

Helpfully, github did inform me after clicking on the hyperlink for the commit that it was part of GaloisInc/saw-script#732, so I was able to figure it out. But we should probably be consistent about using merge commits so that people like me can actually make sense of the git history.

**Comment by brianhuffman** [comment]
@robdockins which branch in which repo are you talking about rebasing? You *definitely* should not rebase the `cryptol-verifier` `split-arith` branch, as this (b46aed94) is the commit that the `saw-script` repo points to as a submodule.

**Comment by robdockins** [comment]
The saw-script module points to an intermediate code change that has since been superseded by 57d90db93e7fabf7d4e2ae3ba97835135e21efd5, which is on `cryptol-verifier/master`.  This `parameterized-file-reader` branch should be rebased onto `cryptol-verifier/master`.

I was waiting a bit to see if Cryptol would quiesce before trying to get a saw-script PR through again, so the submodule lags a bit.

**Comment by brianhuffman** [comment]
Commit 57d90db is on the `split-cmp` branch, and it has not been merged to master either.

**Comment by robdockins** [comment]
Sorry, 2fc49ce9ccc3e259a8f20d258cb8c3078b607dde.  I usually prefer to rebase PRs into master, as it retains a linear history, but it does make situations like this a bit trickier to untangle.

**Comment by brianhuffman** [comment]
Ok, here's my current thinking: First of all, it is absolutely imperative that b46aed9 should never be garbage-collected and disappear from the cryptol-verifier repo, as a master version of saw-script points to this very revision as a submodule, and it is vital that all master versions of saw-script should continue to compile and work correctly.

So what this means is that we need to merge b46aed9 into master, even if all the changes in that branch have already been rebased into master by some other means. I'll make a PR to do that, and then once that's done we can start fixing everything else.

**Comment by kquick** [comment]
Just to complicate things a little more, cryptol master was updated in a way that breaks cryptol-verifier master.  PR #22 is pending to fix cryptol-verifier for that cryptol change.

**Comment by robdockins** [comment]
I think you can tag that commit instead of merging to master if you just want to make sure it doesn't get GCd.

**Comment by david-christiansen** [comment]
It sounds to me like the right approach is for me to wait a bit while things settle down, then revisit this as a need for a release of the Python client approaches. Or am I misunderstanding?

**Comment by robdockins** [comment]
I'll defer to @brianhuffman here, but I've been trying to land patches into `cryptol-verifier` in the same order they land in `cryptol`, so probably #22 should come first.

**Comment by brianhuffman** [comment]
@david-christiansen I've finally straightened out all the cryptol-verifier patches, and applied them in the right order. The current master version of cryptol-verifier (f33f4f234da9f48664f61bd9492b09259c78b60f) descends from the revision you built on (b46aed9412cbdc3313e41095283dd627da28bb7e), and also now works with the current master version of cryptol (GaloisInc/cryptol@6de2283acefe6da562c017f73338d172c79f4f6e).

I also have a saw-script PR that makes saw-script work with the latest cryptol and cryptol-verifier (GaloisInc/saw-script#764).

**Comment by david-christiansen** [comment]
Thanks! 

I suppose the right thing for me to do is to wait for those to get merged in, and then rebase my PR collection on top of them.

**Comment by robdockins** [comment]
@brianhuffman, I think everything is straightened out now, right? I think this should be good to merge.

**Comment by brianhuffman** [comment]
Yeah, it should be good to go.

**Review by brianhuffman — APPROVED** [review]

**Comment by david-christiansen** [comment]
I'm a little unsure of the usual practices on this repo regarding who pushes the merge button. But @kquick pointed out that it's ready to go, so I'll take that as me being the right one now that there's an approval stamp :)

**Pull request merged**
