### PR TITLE
Make test binary load, translate, and typecheck `Cryptol.cry`.

### PR DESCRIPTION
**Pull request by brianhuffman**
(This addresses part of #25.)

### CODE REVIEW

**Comment by brianhuffman** [comment]
Marked as draft until I get the test passing.

**Comment by brianhuffman** [comment]
As of 0042988, the test should be passing.

**Comment by brianhuffman** [comment]
As of dc58a40 (which adds tests of cryptol code exercising all instance and subclass rules), there are a lot of translation failures due to missing class dictionaries. I'll have to implement all of them to get the test passing again.

**Comment by brianhuffman** [comment]
I think this is a good stopping point to merge the PR.

**Review by robdockins — APPROVED** [review]
Seems good to me

**Pull request merged**
